services:
  nginx:
    build:
      context: ./nginx
    volumes:
      - front:/usr/share/nginx/
      - back:/var/www/app/
    ports:
      - "80:80"
      - "8000:8000"

  front:
    build:
      context: ./front
    volumes:
      - front:/app/

  back:
    build:
      context: ./back
    volumes:
      - back:/var/www/app/
    expose:
      - 9000

volumes:
  front:
  back: